include:
  - board: nice_nano_v2
    shield: rolio_left vista508
    snippet: studio-rpc-usb-uart
    artifact-name: zmk-rolio-left
  - board: nice_nano_v2
    shield: rolio_right vista508
    artifact-name: zmk-rolio-right
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: zmk-nicenano_v2-settings_reset