CONFIG_ZMK_KEYBOARD_NAME="mb89.rolio"

# Make Bluetooth stronger
CONFIG_BT_CTLR_TX_PWR_PLUS_8=y

# Enable split battery reporting from peripherals
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

# Fancy bluetooth features
CONFIG_ZMK_BLE_EXPERIMENTAL_FEATURES=y
CONFIG_ZMK_BLE_PASSKEY_ENTRY=y

CONFIG_ZMK_SETTINGS_SAVE_DEBOUNCE=5000

# Enable mouse emulation for scroll encoder bindings
CONFIG_ZMK_POINTING=y

CONFIG_ZMK_BACKLIGHT=y

# Disable ambient light sensor if not populated
# CONFIG_PROSPECTOR_USE_AMBIENT_LIGHT_SENSOR=n
# CONFIG_PROSPECTOR_FIXED_BRIGHTNESS=80
